spring:
  application:
    name: activity-service

  datasource:
    url: jdbc:postgresql://localhost:5432/activity_service_DB
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8082


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
rabbitmq:
  exchange:
    name: activity-exchange
  queue:
    name: activity-queue
  routing:
    key: activity.routing.key
