spring:
  application:
    name: ai-service

  datasource:
    url: jdbc:postgresql://localhost:5432/ai-service
    username: postgres
    password: 123

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


rabbitmq.queue.name: activity_queue
rabbitmq.exchange.name: activity_exchange
rabbitmq.routing.key: activity_routing_key
server:
  port: 8083

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

gemini:
  api:
    url: ${GEMINI_API_URL}
    key: ${GEMINI_API_KEY}
