spring:
  application:
    name: user-profile-service
  datasource:
    url: jdbc:postgresql://localhost:5432/user_profile_db
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8085

# RabbitMQ

rabbitmq:
  host: localhost
  port: 5672
  username: guest
  password: guest